use bank;
alter table account add primary key(Acc_no);
alter table balance add primary key(Bal_Acc_ID, Emp_ID);
alter table borrows add primary key(Loan_ID, Cust_ID);
alter table branch add primary key(IFSC_code);
alter table current_acc add primary key(Acc_no);
alter table customer add primary key(Cust_ID);
alter table depositor add primary key(Cust_ID, Acc_no);
alter table employee add primary key(Emp_ID);
alter table fixed_deposit_acc add primary key(Acc_no);
alter table has add primary key(User_name, User_ID, Role_ID, Per_ID);
alter table loan add primary key(Loan_ID);
alter table locker add primary key(Locker_no);
alter table login add primary key(User_name);
alter table makes add primary key(Loan_ID, Cust_ID);
alter table manage add primary key(User_ID, Cust_ID, Emp_ID);
alter table nri_acc add primary key(Acc_no);
alter table payment add primary key(Pmt_number);
alter table permissions add primary key(Per_ID);
alter table recurring_deposit_acc add primary key(Acc_no);
alter table roles add primary key(Role_ID);
alter table savings_acc add primary key(Acc_no);
alter table user add primary key(User_ID);
